/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package constructor_inheritance;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        SportCar sc = new SportCar("Ferari");
        System.out.println(sc != null);
    }
}
