/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Car myCar = new Car("소나타");
        myCar.start();
        myCar.accelerate();
        myCar.stop();
        System.out.println(myCar.getName());

        System.out.println("============");

        SportCar ferari = new SportCar("Ferari", "Blue");
        ferari.start();
        ferari.accelerate();
        ferari.turboCharge();
        ferari.stop();
        System.out.println(ferari.getName());
        System.out.println("색상 : " + ferari.getColor());
        ferari.setColor("Yellow");
        System.out.println("색상 : " + ferari.getColor());
    }
}