/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.ac.gwnu.computer;

import java.util.ArrayList;
import java.util.Iterator;

public class App {

    public static void main(String[] args) {
        Major computer = new Major("컴퓨터 공학", 3);
        computer.add(new Student("0001", "홍길동"));
        computer.add(new Student("0002", "이몽룡"));
        computer.add(new Student("0003", "심청"));

        for(Student student: computer) {
            System.out.println(student.getName());
        }

        Iterator<Student> studentIterator = computer.iterator();
        while(studentIterator.hasNext()) {
            System.out.println(studentIterator.next().getName());
        }

        ArrayList<String> names = new ArrayList<>();
        names.add("홍길동");
        names.add("이몽룡");
        names.add("심청");
    }
}
