/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.ac.gwnu.com.ch4;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Car car = new Car("SM5");
        car.start();
        System.out.println("차가 출발합니다.");
        System.out.println("속도 : " + car.getSpeed());
        car.accelerate();
        System.out.println("차가 가속합니다.");
        System.out.println("속도 : " + car.getSpeed());
        car.stop();
        System.out.println("차가 정지합니다.");
        System.out.println("속도 : " + car.getSpeed());
        System.out.println("차 이름은 "  + car.getName() + "입니다.");
    }
}
