/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interitance_composition;

public class App {
    public static void main(String[] args) {
        Car myCar = new Car("소나타");
        myCar.carName();
        myCar.start();
        myCar.radioOn();
        myCar.radioOff();
        myCar.stop();
    }
}
